version: "2"
services:
  ushahidi:
    build: .
    volumes:
      - .tars:/tars
    links:
      - mysql
      - redis
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
  redis:
    image: redis:4-alpine
